<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="site/css/normalize.css">
    <link rel="stylesheet" href="site/css/style.css">
    <title>Afrique Partenaires</title>
</head>
<body>
    <div class="container">
        <h1>Afrique Partenaires</h1>
        <nav>
            <button><a href='index.php'>Accueil</a></button>
                <?php 
                    session_start();
                    if (isset($_SESSION['ID'])):
                        ?>
                    
                    <button>Déconnexion</button>
                    <button><a href='index.php?form=profil'>Profil</a></button>
                <?php
                    else:
                ?>
                    <button>Connexion</button>
                    <?php endif; ?>
        </nav>
        <div class="main">
        <?php
                if(isset($_GET['form']))
                    {
                        include($form.$_GET['form'].$phtml);
                        echo $_GET['page'];
                    }
                else
                    {
                        include($form.'article'.$phtml);
                    }
            ?>

        </div>
    </div>
    <script src="site/js/script.js"></script>
</body>
</html>